# Generated by Django 5.2 on 2025-04-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_alter_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, choices=[('Fiction', 'Fiction'), ('Science', 'Science'), ('History', 'History'), ('Romance', 'Romance')], max_length=50, null=True),
        ),
    ]
