# Generated by Django 5.2 on 2025-05-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0006_alter_book_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number_of_copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(default=50),
        ),
    ]
