# Generated by Django 5.2 on 2025-05-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0011_alter_borrower_user_alter_loan_loan_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='borrower',
        ),
    ]
